# 对应{@link com.join.epileptic.util.fileupload.FileUtil.fileUrl}
headPicPath: D:/temp/image/headPic/
spring:
  profiles:
    active: dev
  application:
    name: epileptic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/db_epileptic?useSSL=false&serverTimezone=UTC&charactorEncoding=UTF-8
    username: root
    password: mysql
  resources:
    static-locations: classpath:/static,classpath:/META_INFO,classpath:/templates,file:${headPicPath}
  mvc:
    static-path-pattern: /**

logging:
  level:
    com.join.autism.mapper  : debug
server:
  port: 8890
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.join.epileptic.entity




---
# 对应{@link com.join.epileptic.util.fileupload.FileUtil.fileUrl}
headPicPath: /opt/xiaoy/xl/headPic/
spring:
  profiles: prod
  resources:
    static-locations: classpath:/static,classpath:/META_INFO,classpath:/templates,file:${headPicPath}
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.10.220/db_epileptic?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: Join666
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
server:
  port: 8890